import type { Paper } from "./store";

const HEADER = `// AUTO-GENERATED by the Paper Builder — do NOT hand-edit.
//
// HOW TO USE:
// 1. Save this file to \`src/lib/mcq/papers/bundle.ts\` in your project.
// 2. Open \`src/lib/mcq/index.ts\` and add near the top:
//        import { BUILDER_PAPERS } from "./papers/bundle";
//    then inside \`getPaperQuestions\` change the last line to:
//        return BUILDER_PAPERS[key] ?? REGISTRY[key] ?? null;
// 3. That's it. Every paper you edited in the builder now shows up on the site.
//
// Rebuild the site and each paper page will render its questions.

import type { PaperQuestions } from "../types";
`;

function stringify(value: unknown, indent = 2): string {
  return JSON.stringify(value, null, indent);
}

export function serializeBundle(papers: Record<string, Paper>): string {
  const entries = Object.entries(papers)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, p]) => {
      // strip legacy convenience fields when blocks are present
      const cleaned = p.questions.map((q) => {
        if (q.blocks && q.blocks.length) {
          const { intro: _i, introData: _d, question: _q, order: _o, ...rest } = q;
          return rest;
        }
        return q;
      });
      return `  ${JSON.stringify(id)}: ${stringify(cleaned)}`;
    });
  return `${HEADER}
export const BUILDER_PAPERS: Record<string, PaperQuestions> = {
${entries.join(",\n")}
};
`;
}

export function downloadBundle(papers: Record<string, Paper>) {
  const text = serializeBundle(papers);
  const blob = new Blob([text], { type: "text/typescript" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "bundle.ts";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
