import type { Paper } from "./store";

const LINKS_HEADER = `// AUTO-GENERATED by the Paper Builder — do NOT hand-edit.
//
// Save this file to \`src/lib/paper-links.ts\` in your project.

import type { SubjectId, SessionId } from "./papers-data";

const SUBJECT_CODE: Record<SubjectId, string> = {
  biology: "0610",
  chemistry: "0620",
  physics: "0625",
};

const SESSION_CODE: Record<SessionId, string> = {
  feb: "m",
  june: "s",
  oct: "w",
};

export type PaperLink = {
  qp?: string | null;
  ms?: string | null;
};
`;

const LINKS_FOOTER = `
function defaultUrl(
  subject: SubjectId,
  year: number,
  session: SessionId,
  variant: string,
  kind: "qp" | "ms",
) {
  const yy = String(year).slice(-2);
  const v = variant.replace(/^V/i, "");
  return \`https://dynamicpapers.com/wp-content/uploads/2015/09/\${SUBJECT_CODE[subject]}_\${SESSION_CODE[session]}\${yy}_\${kind}_2\${v}.pdf\`;
}

export function getPaperLinks(
  subject: SubjectId,
  year: number,
  session: SessionId,
  variant: string,
): { qp: string | null; ms: string | null } {
  const key = \`\${subject}-\${year}-\${session}-\${variant}\`;
  const override = OVERRIDES[key] ?? {};
  return {
    qp:
      override.qp === null
        ? null
        : (override.qp ?? defaultUrl(subject, year, session, variant, "qp")),
    ms:
      override.ms === null
        ? null
        : (override.ms ?? defaultUrl(subject, year, session, variant, "ms")),
  };
}
`;

export function serializePaperLinks(papers: Record<string, Paper>): string {
  const entries = Object.entries(papers)
    .filter(
      ([, p]) => p.meta?.links && (p.meta.links.qp !== undefined || p.meta.links.ms !== undefined),
    )
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, p]) => `  ${JSON.stringify(id)}: ${JSON.stringify(p.meta!.links)}`);
  return `${LINKS_HEADER}
const OVERRIDES: Record<string, PaperLink> = {
${entries.join(",\n")}${entries.length ? "," : ""}
};
${LINKS_FOOTER}`;
}

const GB_HEADER = `// AUTO-GENERATED by the Paper Builder — do NOT hand-edit.
//
// Save this file to \`src/lib/mcq/grade-boundaries.ts\` in your project.

import type { SubjectId, SessionId } from "@/lib/papers-data";

export type GradeSystem = "ag" | "91";
export type Boundaries = Record<string, number>;

export type GradeInfo = {
  boundaries: Partial<Record<GradeSystem, Boundaries>>;
  links: Partial<Record<GradeSystem, string>>;
};
`;

const GB_FOOTER = `
export function getGradeInfo(
  subject: SubjectId,
  year: number,
  session: SessionId,
  variant: string,
): GradeInfo | null {
  return REGISTRY[\`\${subject}-\${year}-\${session}-\${variant}\`] ?? null;
}

export function computeGrade(score: number, b: Boundaries): string | null {
  const entries = Object.entries(b).sort((a, z) => z[1] - a[1]);
  for (const [g, min] of entries) if (score >= min) return g;
  return null;
}

export function gradeSystemLabel(s: GradeSystem) {
  return s === "ag" ? "A–G" : "9–1";
}
`;

export function serializeGradeBoundaries(papers: Record<string, Paper>): string {
  const rows: string[] = [];
  for (const [id, p] of Object.entries(papers).sort(([a], [b]) => a.localeCompare(b))) {
    const b = p.meta?.boundaries;
    if (!b || !Object.keys(b).length) continue;
    const boundaries: Record<string, Record<string, number>> = {};
    const links: Record<string, string> = {};
    for (const sys of ["ag", "91"] as const) {
      const entry = b[sys];
      if (!entry) continue;
      if (entry.grades && Object.keys(entry.grades).length) boundaries[sys] = entry.grades;
      if (entry.link) links[sys] = entry.link;
    }
    if (!Object.keys(boundaries).length && !Object.keys(links).length) continue;
    rows.push(
      `  ${JSON.stringify(id)}: {\n    boundaries: ${JSON.stringify(boundaries)},\n    links: ${JSON.stringify(links)},\n  }`,
    );
  }
  return `${GB_HEADER}
const REGISTRY: Record<string, GradeInfo> = {
${rows.join(",\n")}${rows.length ? "," : ""}
};
${GB_FOOTER}`;
}

export function downloadTextFile(filename: string, content: string, mime = "text/typescript") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
