import type { PaperQuestions } from "@/lib/mcq/types";

/**
 * Serialize a PaperQuestions array into a ready-to-drop TypeScript file
 * that matches the shape used in src/lib/mcq/papers/*.ts.
 *
 * The exported constant body is emitted as strict JSON so it can be parsed
 * back on import (see parse.ts). Image `src` values are kept as-is — for
 * built-in-builder papers we store data URLs directly in the file.
 */
export function serializePaperToTS(
  questions: PaperQuestions,
  exportName: string,
): string {
  const json = JSON.stringify(questions, null, 2);
  return `import type { PaperQuestions } from "../types";

/* eslint-disable */
// Generated by the in-app Paper Builder — drop this file into
// src/lib/mcq/papers/ and register it in src/lib/mcq/index.ts.
export const ${exportName}: PaperQuestions = ${json};
`;
}

export function serializePaperToJSON(questions: PaperQuestions): string {
  return JSON.stringify(questions, null, 2);
}

export function downloadTextFile(
  filename: string,
  content: string,
  mime = "text/plain",
) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}