/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McqIndexRouteImport } from './routes/mcq.index'
import { Route as McqBookmarksRouteImport } from './routes/mcq.bookmarks'
import { Route as McqSubjectIndexRouteImport } from './routes/mcq.$subject.index'
import { Route as ApiAiCompleteRouteImport } from './routes/api/ai.complete'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as McqSubjectYearIndexRouteImport } from './routes/mcq.$subject.$year.index'
import { Route as McqSubjectYearSessionIndexRouteImport } from './routes/mcq.$subject.$year.$session.index'
import { Route as McqSubjectYearSessionVariantRouteImport } from './routes/mcq.$subject.$year.$session.$variant'

const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McqIndexRoute = McqIndexRouteImport.update({
  id: '/mcq/',
  path: '/mcq/',
  getParentRoute: () => rootRouteImport,
} as any)
const McqBookmarksRoute = McqBookmarksRouteImport.update({
  id: '/mcq/bookmarks',
  path: '/mcq/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const McqSubjectIndexRoute = McqSubjectIndexRouteImport.update({
  id: '/mcq/$subject/',
  path: '/mcq/$subject/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCompleteRoute = ApiAiCompleteRouteImport.update({
  id: '/api/ai/complete',
  path: '/api/ai/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const McqSubjectYearIndexRoute = McqSubjectYearIndexRouteImport.update({
  id: '/mcq/$subject/$year/',
  path: '/mcq/$subject/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const McqSubjectYearSessionIndexRoute =
  McqSubjectYearSessionIndexRouteImport.update({
    id: '/mcq/$subject/$year/$session/',
    path: '/mcq/$subject/$year/$session/',
    getParentRoute: () => rootRouteImport,
  } as any)
const McqSubjectYearSessionVariantRoute =
  McqSubjectYearSessionVariantRouteImport.update({
    id: '/mcq/$subject/$year/$session/$variant',
    path: '/mcq/$subject/$year/$session/$variant',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/mcq/bookmarks': typeof McqBookmarksRoute
  '/mcq/': typeof McqIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
  '/mcq/$subject/': typeof McqSubjectIndexRoute
  '/mcq/$subject/$year/': typeof McqSubjectYearIndexRoute
  '/mcq/$subject/$year/$session/$variant': typeof McqSubjectYearSessionVariantRoute
  '/mcq/$subject/$year/$session/': typeof McqSubjectYearSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/mcq/bookmarks': typeof McqBookmarksRoute
  '/mcq': typeof McqIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
  '/mcq/$subject': typeof McqSubjectIndexRoute
  '/mcq/$subject/$year': typeof McqSubjectYearIndexRoute
  '/mcq/$subject/$year/$session/$variant': typeof McqSubjectYearSessionVariantRoute
  '/mcq/$subject/$year/$session': typeof McqSubjectYearSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/mcq/bookmarks': typeof McqBookmarksRoute
  '/mcq/': typeof McqIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
  '/mcq/$subject/': typeof McqSubjectIndexRoute
  '/mcq/$subject/$year/': typeof McqSubjectYearIndexRoute
  '/mcq/$subject/$year/$session/$variant': typeof McqSubjectYearSessionVariantRoute
  '/mcq/$subject/$year/$session/': typeof McqSubjectYearSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/mcq/bookmarks'
    | '/mcq/'
    | '/api/ai/chat'
    | '/api/ai/complete'
    | '/mcq/$subject/'
    | '/mcq/$subject/$year/'
    | '/mcq/$subject/$year/$session/$variant'
    | '/mcq/$subject/$year/$session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/mcq/bookmarks'
    | '/mcq'
    | '/api/ai/chat'
    | '/api/ai/complete'
    | '/mcq/$subject'
    | '/mcq/$subject/$year'
    | '/mcq/$subject/$year/$session/$variant'
    | '/mcq/$subject/$year/$session'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/mcq/bookmarks'
    | '/mcq/'
    | '/api/ai/chat'
    | '/api/ai/complete'
    | '/mcq/$subject/'
    | '/mcq/$subject/$year/'
    | '/mcq/$subject/$year/$session/$variant'
    | '/mcq/$subject/$year/$session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  McqBookmarksRoute: typeof McqBookmarksRoute
  McqIndexRoute: typeof McqIndexRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiCompleteRoute: typeof ApiAiCompleteRoute
  McqSubjectIndexRoute: typeof McqSubjectIndexRoute
  McqSubjectYearIndexRoute: typeof McqSubjectYearIndexRoute
  McqSubjectYearSessionVariantRoute: typeof McqSubjectYearSessionVariantRoute
  McqSubjectYearSessionIndexRoute: typeof McqSubjectYearSessionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/': {
      id: '/mcq/'
      path: '/mcq'
      fullPath: '/mcq/'
      preLoaderRoute: typeof McqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/bookmarks': {
      id: '/mcq/bookmarks'
      path: '/mcq/bookmarks'
      fullPath: '/mcq/bookmarks'
      preLoaderRoute: typeof McqBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/$subject/': {
      id: '/mcq/$subject/'
      path: '/mcq/$subject'
      fullPath: '/mcq/$subject/'
      preLoaderRoute: typeof McqSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/complete': {
      id: '/api/ai/complete'
      path: '/api/ai/complete'
      fullPath: '/api/ai/complete'
      preLoaderRoute: typeof ApiAiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/$subject/$year/': {
      id: '/mcq/$subject/$year/'
      path: '/mcq/$subject/$year'
      fullPath: '/mcq/$subject/$year/'
      preLoaderRoute: typeof McqSubjectYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/$subject/$year/$session/': {
      id: '/mcq/$subject/$year/$session/'
      path: '/mcq/$subject/$year/$session'
      fullPath: '/mcq/$subject/$year/$session/'
      preLoaderRoute: typeof McqSubjectYearSessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/$subject/$year/$session/$variant': {
      id: '/mcq/$subject/$year/$session/$variant'
      path: '/mcq/$subject/$year/$session/$variant'
      fullPath: '/mcq/$subject/$year/$session/$variant'
      preLoaderRoute: typeof McqSubjectYearSessionVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  McqBookmarksRoute: McqBookmarksRoute,
  McqIndexRoute: McqIndexRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiCompleteRoute: ApiAiCompleteRoute,
  McqSubjectIndexRoute: McqSubjectIndexRoute,
  McqSubjectYearIndexRoute: McqSubjectYearIndexRoute,
  McqSubjectYearSessionVariantRoute: McqSubjectYearSessionVariantRoute,
  McqSubjectYearSessionIndexRoute: McqSubjectYearSessionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
